### ISSUE TITLE
Unpin versions of most dependencies

### ISSUE THREAD

**Issue by jordanperr** [NREL/OpenOA#228]
This issue consolidates issues #178 and #167 

We want to unpin the dependencies in setup.py so that downstream packages (such as the ENTR runtime) don't have to keep downgrading packages to specific versions. The last time this was attempted, we have the following two issues:

- [x] QA Module fails to load due to missing H5PYD dependency, #116 and #220
- [x] Test failure after updating to Pandas 1.3.0 #167 - Tests fail due to small changes in outputs.
- [x] Evaluate new behavior of GradientBoostedModel in scikit-learn > 1.0 and update OpenOA to use new version #178 - Potentially related to #167.
- [x] Unpin versions of all dependencies to latest versions, re-run tests.
- [x] Unpin Python version (right now it's pinned at 3.9)

**Comment by RHammond2** [comment]
@jordanperr I have this in the works, can return to it next week. There are some pretty trivial changes in test results at this point as well, so it doesn't seem particularly worthwhile to do a waterfall analysis of the changes.

**Comment by RHammond2** [comment]
@jordanperr  can you confirmed that this was closed with #226? It appears to be so, but just want your stamp of approval.

**Comment by jordanperr** [comment]
This can be closed. I moved the un-finished part of this to a new issue #239.
